# Generated by Django 5.0.3 on 2024-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_domaininterest_projectsdone_skill_userinfo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="available",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("working", "Working on the Project"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="city",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="domain",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="domain_interest",
            field=models.ManyToManyField(
                blank=True, default=None, to="blog.domaininterest"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="phone_number",
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="projects_done",
            field=models.ManyToManyField(
                blank=True, default=None, to="blog.projectsdone"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="skills",
            field=models.ManyToManyField(blank=True, default=None, to="blog.skill"),
        ),
    ]
