# Generated by Django 5.0.3 on 2024-03-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_userinfo_available_userinfo_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="projects",
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="skillss",
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="domain",
            field=models.CharField(default=None, max_length=120),
        ),
    ]
