# Generated by Django 5.0.3 on 2024-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_userinfo_projects_userinfo_skillss_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="domain",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
