# Generated by Django 5.0.3 on 2024-03-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_userinfo_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="available",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("working", "Working on the Project"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
