# Generated by Django 5.0.3 on 2024-03-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_userinfo_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="department",
            field=models.CharField(
                choices=[
                    ("ECE", "ECE"),
                    ("MECH", "Mech"),
                    ("CSE", "CSE"),
                    ("AIDS", "AIDS"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="github",
            field=models.CharField(default="", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="linkedin",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="year",
            field=models.CharField(
                choices=[("I", "I"), ("II", "II"), ("III", "III"), ("IV", "IV")],
                default="available",
                max_length=20,
            ),
        ),
    ]
