# Generated by Django 5.0.3 on 2024-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_userinfo_department_userinfo_github_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="github",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="linkedin",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
