# Generated by Django 5.0.3 on 2024-03-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_userinfo_github_alter_userinfo_linkedin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="about",
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="department",
            field=models.CharField(
                choices=[
                    ("ECE", "ECE"),
                    ("MECH", "Mech"),
                    ("CSE", "CSE"),
                    ("AIDS", "AIDS"),
                ],
                default="CSE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="year",
            field=models.CharField(
                choices=[("I", "I"), ("II", "II"), ("III", "III"), ("IV", "IV")],
                default="I",
                max_length=20,
            ),
        ),
    ]
