# Generated by Django 5.0.3 on 2024-03-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_userinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='github',
            field=models.URLField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='linkedin',
            field=models.URLField(default='', max_length=100, null=True),
        ),
    ]
